  language: python
  python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
  install:
    - pip install coveralls
    - pip install coverage
  script:
    - python setup.py install
    - coverage run test.py -v
  after_success:
    - coveralls
